// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArfltF0rzv67HnlJzL3awSJKZgVUsMoOQ',
    appId: '1:950995253198:web:e34d89cbfd9c7701a5dd9f',
    messagingSenderId: '950995253198',
    projectId: 'loginpsi-787cd',
    authDomain: 'loginpsi-787cd.firebaseapp.com',
    storageBucket: 'loginpsi-787cd.appspot.com',
    measurementId: 'G-GN7CFCZD23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApwnyZHJgO9JRVwV1DlhiR7NDZNLFPpgw',
    appId: '1:950995253198:android:2d554bdda8bc3e65a5dd9f',
    messagingSenderId: '950995253198',
    projectId: 'loginpsi-787cd',
    storageBucket: 'loginpsi-787cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHXO2vDVkouLLroVxZy7jJ43qUY9unhJ0',
    appId: '1:950995253198:ios:9d35a66ff243ec4fa5dd9f',
    messagingSenderId: '950995253198',
    projectId: 'loginpsi-787cd',
    storageBucket: 'loginpsi-787cd.appspot.com',
    iosClientId: '950995253198-sar7bnc4ie0qh5t6hgejgpi6ovko7vp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHXO2vDVkouLLroVxZy7jJ43qUY9unhJ0',
    appId: '1:950995253198:ios:9d35a66ff243ec4fa5dd9f',
    messagingSenderId: '950995253198',
    projectId: 'loginpsi-787cd',
    storageBucket: 'loginpsi-787cd.appspot.com',
    iosClientId: '950995253198-sar7bnc4ie0qh5t6hgejgpi6ovko7vp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
